FROM amazoncorretto:21.0.3-alpine3.19

# Set the working directory
WORKDIR /app

# Copy the built jar file
COPY build/libs/regexManager-*.jar app.jar
# Copy the environement file
COPY .env .env




# Command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]